Name:           ros-melodic-franka-example-controllers
Version:        0.6.0
Release:        1%{?dist}
Summary:        ROS franka_example_controllers package

Group:          Development/Libraries
License:        Apache 2.0
URL:            http://wiki.ros.org/franka_example_controllers
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-controller-interface
Requires:       ros-melodic-dynamic-reconfigure
Requires:       ros-melodic-franka-control
Requires:       ros-melodic-franka-description
Requires:       ros-melodic-franka-hw
Requires:       ros-melodic-geometry-msgs
Requires:       ros-melodic-hardware-interface
Requires:       ros-melodic-libfranka
Requires:       ros-melodic-message-runtime
Requires:       ros-melodic-panda-moveit-config
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-realtime-tools
Requires:       ros-melodic-roscpp
Requires:       ros-melodic-rospy
BuildRequires:  eigen3-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-controller-interface
BuildRequires:  ros-melodic-dynamic-reconfigure
BuildRequires:  ros-melodic-franka-hw
BuildRequires:  ros-melodic-geometry-msgs
BuildRequires:  ros-melodic-hardware-interface
BuildRequires:  ros-melodic-libfranka
BuildRequires:  ros-melodic-message-generation
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-realtime-tools
BuildRequires:  ros-melodic-roscpp

%description
franka_example_controllers provides example code for controlling Franka Emika
research robots with ros_control

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Jul 11 2019 Franka Emika GmbH <support@franka.de> - 0.6.0-1
- Autogenerated by Bloom

